spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: provider-config-liuyangjun-dev
---
spring:
  profiles: test
  application:
    name: provider-config-liuyangjun-test